WIP fix for #243
LedgerHQ/speculos pull request #244
Opened 2021-08-11 11:17 UTC by kingofpayne

2021-08-16 11:53 UTC, greenknot requested changes
Thanks @kingofpayne. I'm not familiar with https://docs.python.org/3/library/contextlib.html, however it LGTM.

2021-08-16 11:53 UTC, greenknot commented on speculos/client.py
> +    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
Please add type annotation for all arguments.

FYI, it was found with:

```console
$ mypy --strict speculos/client.py
speculos/client.py:199: error: Function is missing a type annotation for one or more arguments
```

unfortunately `mypy` warnings should be fixed across the entire code base before being integrated to the CI.

2021-08-18 13:51 UTC, kingofpayne commented
Updated `client.py` to start and stop correctly both speculos and event streaming.
It is also now possible to call manually `start` and `stop` on `SpeculosInstance` if the user is not willing to use `with` statement.

Also added typing for `SpeculosInstance.__exit__`.

2021-11-25 08:16 UTC, greenknot approved these changes

2021-11-25 08:26 UTC, merged