LNS+ SDK 1.0 support
LedgerHQ/speculos pull request #271
Opened 2022-02-07 14:29 UTC by cbouvet-ledger

2022-02-17 15:42 UTC, greenknot requested changes

2022-02-17 15:42 UTC, greenknot commented on src/emulate_lnsp_1.0.c
> +#define _SDK_2_0_
I'm not sure about this file, let's talk about it offline.

2022-03-16 15:19 UTC, greenknot requested changes
I made a few minor comments, if you can address them before merging it'd be great. Thanks for the PR!

2022-03-18 11:25 UTC, Saltari commented on tests/apps/conftest.py
> -    app_regexp = re.compile(r"^(nanos|nanox|blue)#([^#]+)#([^#][\d\w\-.]+)#([a-f0-9]{8})\.elf$")
done

2022-03-18 11:26 UTC, Saltari commented on src/emulate_lnsp_1.0.c
> +#define _SDK_2_0_
it is used actually in the syscalls header to know if we use the old syscall system with ID_IN/ID_OUT or the the new one.
it does not compile without this define

2022-03-18 12:53 UTC, greenknot approved these changes

2022-03-18 12:57 UTC, merged