docker: Add pyqt5 dependency
LedgerHQ/speculos pull request #541
Opened 2024-12-19 15:41 UTC by aussedatlo

This PR aims to add pyqt5 support to be able to run speculos with qt.

WARNING: As the qt library is not very light, the image size is now 1.56GB instead of 800MB.

I changed the base image from `docker.io/library/python:3.9-slim` to `debian:bookworm-slim` to be able to use the `apt` `python3-pyqt5` package that is already compiled.

2025-03-21 09:01 UTC, yogh333 requested changes
Could you please rebase your PR 🙏

2025-03-24 10:27 UTC, aussedatlo commented
Updated the PR, also bumped python version to `9.10` to match builder version.

2025-03-25 14:56 UTC, yogh333 approved these changes
LGTM

2025-03-27 14:06 UTC, aussedatlo commented
Hello, do you know when we can merge this PR?

2025-04-18 16:30 UTC, cedelavergne-ledger commented
No more relevant, since we have migrated to pyqt6

2025-04-18 16:30 UTC, closed without merging